### ISSUE TITLE
Error in V[j, ] <- V[j, ] + lambda * (sigma * (-U[u, ]) - regJ * V[j,  :    NAs are not allowed in subscripted assignments

### ISSUE THREAD

**Issue by perfectatdat** [ludovikcoba/rrecsys#1]
I am getting this error 

  Error in V[j, ] <- V[j, ] + lambda * (sigma * (-U[u, ]) - regJ * V[j,  :    NAs are not allowed in sub-scripted
 assignments

on default settings, although there are no NAs in the dataset. When i set the lambda to 0.001 then I get the following error;

  Error in U[u, ] <- U[u, ] + lambda * (sigma * (V[i, ] - V[j, ]) - regU *  : 
  replacement has length zero

[AprUsg1.zip](https://github.com/ludovikcoba/rrecsys/files/347096/AprUsg1.zip)

**Comment by ludovikcoba** [comment]
I am sorry for the late answer.
I tried to train a model with the BPR algorithm on the MovieLens dataset but I don't get that error. 
Please double check your matrix for NAs(command: any(is.na(yourMatrix)) ). 
The file you have attached is empty.

**Comment by ludovikcoba** [comment]
NA will be changed to a 0 in any rating matrix.
