### ISSUE TITLE
nDCG per user other than per fold

### ISSUE THREAD

**Issue by jonnylee719** [ludovikcoba/rrecsys#4]
Another thing is with the returned metric values. To do statistical tests, e.g. t-tests, more samples are needed and by increasing number of folds just to get over 30 samples is simply too time costly. I have tried modifying the ```evalRec.R``` file with 
`# Combine the normal res with the nDCG per folds as a list`
`res <- list(res, nDCG_folds)`
where nDCG_folds contains all the nDCG per users. But I feel like there could be a much more elegant solution where the user can easily access the metric value per user with result. I would be happy to try and help implement something.

**Comment by ludovikcoba** [comment]
That wouldn't be that much trouble for me. But consider the fact that I am doing _k-fold cross validation_, so you will get _k_ values of the nDCG for each user. 
If you are interested only in the nDCG(on each user), I can implement a new function only for that.
Let me know.

**Comment by jonnylee719** [comment]
Yea, I had a look at the code, there are k values of the nDCG for each user. But you normally only get the nDCG per fold as the result rather than the individual k values of the nDCG for each user or the nDCG (on each user). Please do tell me if I am mistaken.

**Comment by ludovikcoba** [comment]
You are right, the nDCG function computes it on each user and later it is computed over the entire fold(the reported value) on the evalPred function, this operation is repeated k-times.

**Comment by jonnylee719** [comment]
So do you think it would be useful to also provide individual nDCF per user so that we can compare the performance between algorithms by statistical tests like t-test or Wilcoxon rank sum test?

**Comment by ludovikcoba** [comment]
Depends on what you are trying to achieve. In this implementation I followed literature and as well other implementation in popular recommender environments. Let me point out that this is not an Issue but it stands more as a request, which I would be glad to help you out with.

**Comment by jonnylee719** [comment]
Yea it is a request, and I am very grateful and glad to hear that you would be able to help. Thank you! And I apologize if I came across as being ill-mannered at any point.

**Comment by ludovikcoba** [comment]
You weren't ill-mannered at all, but let me close the issue and we can continue the discussion via e-mail.
